# Generated by Django 4.1.6 on 2023-02-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_shops', '0001_initial'),
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(related_name='order_items', to='app_shops.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ManyToManyField(related_name='order_items', to='app_shops.shop', verbose_name='Магазин'),
        ),
    ]
