# Generated by Django 4.1.6 on 2023-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_remove_orderitem_product_remove_orderitem_shop_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order_id',), name='unique_order_item'),
        ),
    ]
