# Generated by Django 4.1.6 on 2023-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='model',
            field=models.CharField(default=0, max_length=80, verbose_name='Модель'),
        ),
    ]
