# Generated by Django 4.1.6 on 2023-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_productinfo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Внешний ИД'),
        ),
    ]
